# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build1:

    runs-on: windows-2022

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore

    - name: Generate resources
      run: cd Resgen && dotnet run --no-restore -f net6.0
      
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.1
      with:
        msbuild-architecture: x64
    - name: Run Test version 4.5.2
      run: dotnet vstest .\tests\bin\Debug\net452\*.dll /Platform:x64 /Framework:".NETFramework,Version=v4.5.2"
    - name: Run Test version 4.6.0
      run: dotnet vstest .\tests\bin\Debug\net46\*.dll /Platform:x64 /Framework:".NETFramework,Version=v4.6.0"
    - name: Run Test version 4.6.2
      run: dotnet vstest .\tests\bin\Debug\net462\*.dll /Platform:x64 /Framework:".NETFramework,Version=v4.6.2"
    - name: Run Test version 4.7.0
      run: dotnet vstest .\tests\bin\Debug\net47\*.dll /Platform:x64 /Framework:".NETFramework,Version=v4.7.0"
    - name: Run Test version 4.7.2
      run: dotnet vstest .\tests\bin\Debug\net472\*.dll /Platform:x64 /Framework:".NETFramework,Version=v4.7.2"
    - name: Run Test version 4.8.0
      run: dotnet vstest .\tests\bin\Debug\net48\*.dll /Platform:x64 /Framework:".NETFramework,Version=v4.8.0"
    - name: Run Test version 4.8.1
      run: dotnet vstest .\tests\bin\Debug\net481\*.dll /Platform:x64 /Framework:".NETFramework,Version=v4.8.1"
